apiVersion: v1
kind: Service
metadata: 
  name: pru-service
spec:
  selector:
    app: pru-app-label
  ports:
    - protocol: "TCP"
      port: 8081
      targetPort: 8081
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pru-deployment
#  labels:
#    app: pru-app-label
spec:
  selector:
    matchLabels:
      app: pru-app-label
  template:
        metadata:
          labels:
             app: pru-app-label
        spec:
          containers:
              - name: pru-container
                image: springbootdemotest
                imagePullPolicy: IfNotPresent
                ports:
                  - containerPort: 8081
           
            